apiVersion: v2
name: argocd
description: ArgoCD deployment for GitOps

type: application

version: 0.1.0

appVersion: "1.16.0"

# Dependencies - use official ArgoCD Helm chart
dependencies:
  - name: argo-cd
    version: 7.7.7
    repository: https://argoproj.github.io/argo-helm
